FROM ubuntu

ENV DEBIAN_FRONTEND=noninteractive
RUN sed -i 's/^exit 101/exit 0/' /usr/sbin/policy-rc.d

RUN \
    apt-get update && \
    apt-get install -y ca-certificates && \
    apt-get install -y curl && \
    rm -rf /var/lib/apt/lists/* && \
    cd && \
    mkdir eic

ADD /root/eic /Users/linonon/Workspace/MyMacConfig/README.md 
ENTRYPOINT ["root/eic"]